### ISSUE TITLE
Error in summing up ghg_s1s2 for TETS method

### ISSUE THREAD

**Issue by alexanu** [os-climate/ITR#104]
If we use TETS method for portfolio aggregation total emissions are used for weighting portfolio members. For now these are mainly coming from column [2020_ghg_s1s2] on the "ITR input data" tab. However when calculating sum of values in column (`portfolio_aggregation.py`) ...
![grafik](https://user-images.githubusercontent.com/16149724/171444785-0a0aa419-a6aa-4baa-b7c8-6c011ec8d656.png)

.... the values with decimal separator (which is comma) are taken with factor 1 000 000

Maybe it comes from pint thing?

**Comment by MichaelTiemannOSC** [comment]
Closing as resolved by above pull request.
