### ISSUE TITLE
Update subtitle on dashboard report

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/ITR#175]
Now that the tool is more robust, supporting multiple sectors and no longer a prototype - subtitle should be changed to something like "Tool for calculating the Implied Temperature Rise for a sector-specific investment portfolio such as steel, utilities, chemicals, etc."  Current text:
![image](https://user-images.githubusercontent.com/90428947/210419779-50efa92f-ca04-4245-950f-31f9615f736d.png)

**Comment by MichaelTiemannOSC** [comment]
This was closed by c987c4d75657516ed349ee747af5d631ea2fcb9b
