### ISSUE TITLE
unittest vs pytest

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/ITR#21]
I just saw this issue filed in the PUDL github: https://github.com/catalyst-cooperative/pudl/issues/1357

I wonder what are the pros/cons of unittest (which ITR uses) vs pytest for our future plans.

@caldeirav @erikerlandson @HeatherAck

**Comment by MichaelTiemannOSC** [comment]
Reupping this...we should convert to pytest, which can then be used as acceptance testing for platform as well as ITR QA.

@HeatherAck

**Comment by kmarinushkin** [comment]
It seems to me, that we already use ‘pytest’ for unit tests.
And it works.
I maybe don't understand what we discuss in this GitHub issue

**Comment by MichaelTiemannOSC** [comment]
If you have been using pytest, great!  I've been using `python -m unittest discover test`

**Comment by kmarinushkin** [comment]
you already now can use `pytest` with our existing tests.

pre-conditions:

* in console, you activated virtual python environment (in our Readme steps, it's called `itr_ui`)
* navigate to `ITR` folder
* export `PYTHONPATH=..:.:itr_ui/lib/python3.9/site-packages` - it will add parent folder, current folder, and virtual environment folder to python module search

run test:

* `pytest test/test_base_providers.py`

---

what i want to say is: there seems to be nothing more to do, in the context of this Guthub issue
* pytest test/test_base_providers.py

**Comment by MichaelTiemannOSC** [comment]
Agreed!  I ran `pytest test` and it processed the directory as expected.  Closing it out.
