### ISSUE TITLE
Developers need help getting DCO correctly working

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/ITR#39]
@MichaelTiemannOSC and @dp90 have many checkins that do not have a proper sign-off: https://github.com/os-climate/ITR/pull/29/checks?check_run_id=5372811325

I have tried to do this correctly in other streams (data ingestion) and clearly don't understand what I need to do.  I also have not-fond memories of trying to fix what I don't understand when it comes to GitHub.  Help appreciated.

**Comment by MichaelTiemannOSC** [comment]
An update: When using git from the command line and a proper GITHUB_TOKEN environment variable, `git commit -s` has the right sauce and the changes are accepted as expected.  When I don't have a GITHUB_TOKEN environment variable set (which happens), `git commit -s` happily provides a commit message with the signature `Signed-off-by: MichaelTiemannOSC  <mtiemann@os-climate.org>`, making me think I'm following instructions correctly.

But that's wrong.

And GitHub makes me pay.

Because it rejects the DCO not signed with special sauce.

Which makes me sad.  And forces me to waste time chasing down the fixes for something that should never have been broken in the first place.

**Comment by HeatherAck** [comment]
Adding @MightyNerdEric to see if this can be fixed

**Comment by MichaelTiemannOSC** [comment]
This has all been sorted, for now.
