### ISSUE TITLE
MyPy Linting Warnings

### ISSUE THREAD

**Issue by ModeSevenIndustrialSolutions** [os-climate/ITR#493]
We should almost certainly fix these MyPy linting warnings:

> mypy.....................................................................Failed
> - hook id: mypy
> - duration: 0.87s
> - exit code: 1
> - src/ITR/data/base_providers.py:781: error: "ProductionBenchmarkDataProvider" has no attribute "_get_projected_production"; maybe "get_company_projected_production"?  [attr-defined]
> src/ITR/data/base_providers.py:2327: error: Item "None" of "ICompanyEIProjections | None" has no attribute "projections"  [union-attr]
> Found 2 errors in 1 file (checked 29 source files)

**Comment by MichaelTiemannOSC** [comment]
Should be fixed by https://github.com/os-climate/ITR/pull/498
